name: examen_compu_movil
description: "Login con FirebaseAuth + CRUD REST (Productos, Categorías, Proveedores)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
